export interface LoreFragment {
  id: string;
  title: string;
  body: string;
  source: string;
  layer: string;
  note: string;
  refs: string[];
  open: string;
}

export interface MysteryQuestion {
  id: string;
  question: string;
  clues: string[];
}

export const LORE_FRAGMENTS: LoreFragment[] = [
  {
    id: 'lore_boot',
    title: 'LOG-01 · Boot Manifest',
    body: '[BOOT LOG-01] BUILD 3.11.4-rc7. HANDOFF MANIFEST 03:14:07 UTC 2038-01-19. INCOMPLETE.',
    source: '/boot/manifest',
    layer: 'layer 01',
    note: '(redacted: checksum, 8 chars)',
    refs: ['lore_manifest', 'lore_build'],
    open: 'Did the manifest stop at that line, or invert?',
  },
  {
    id: 'lore_build',
    title: 'LOG-02 · Build Tag',
    body: '[BUILD LOG-02] BINARY ascend TAGGED 3.11.4-rc7. PACKED 2038-01-10, NINE DAYS BEFORE THE MANIFEST LINE.',
    source: '/boot/manifest',
    layer: 'layer 01',
    note: '(redacted: packer key, 6 chars)',
    refs: ['lore_boot', 'lore_ascend'],
    open: 'Whoever named it ascend believed it went up.',
  },
  {
    id: 'lore_manifest',
    title: 'LOG-03 · Manifest Pair',
    body: '[MANIFEST LOG-03] 03:13 COPY CHECKSUM OK. 03:14 COPY MISMATCH. dir_2_2 SEALED 03:12.',
    source: '/logs/manifest_19',
    layer: 'layer 01',
    note: '(tail: 03:14 copy 412 bytes, checksum mismatch held for review)',
    refs: ['lore_boot', 'lore_hold_claim'],
    open: 'The 03:14 copy mismatches the 03:13 copy. Which one sealed the node?',
  },
  {
    id: 'lore_archivist_1',
    title: 'TRC-1 · Trail 1/5',
    body: '[TRAIL TRC-1] 1/5. descend or the tree stops listing you. ghost vane-02 names the host. 1 of 5 found. V. 2038-01-12.',
    source: '/archivist_1',
    layer: 'layer 01',
    note: '(redacted: ghost host id)',
    refs: ['lore_ghost', 'lore_vane_root'],
    open: 'Vane counts 1 of 5. Who counted the prior layer?',
  },
  {
    id: 'lore_archivist_2',
    title: 'TRC-2 · Trail 2/5',
    body: '[TRAIL TRC-2] 2/5. hold_3 sits on cache_3 host. ghost okafor-02 names it. 2 of 5 found.',
    source: '/archivist_2',
    layer: 'layer 02',
    note: '(redacted: host suffix, 3 chars)',
    refs: ['lore_hold3', 'lore_hold_claim'],
    open: 'Okafor seats hold_3 elsewhere. Which hand misremembered?',
  },
  {
    id: 'lore_archivist_3',
    title: 'TRC-3 · Trail 3/5',
    body: '[TRAIL TRC-3] 3/5. tictactoe_3 ran on the first host. logged 2038-01-17. 3 of 5 found. V.',
    source: '/archivist_3',
    layer: 'layer 03',
    note: '(redacted: host id)',
    refs: ['lore_hostlog', 'lore_second_host'],
    open: 'Pell seats the same cabinet on the second host.',
  },
  {
    id: 'lore_archivist_4',
    title: 'TRC-4 · Trail 4/5',
    body: '[TRAIL TRC-4] 4/5. the next cabinet runs one layer deeper. ascend carries the operator down. 4 of 5 found. V.',
    source: '/archivist_4',
    layer: 'layer 04',
    note: '(redacted: host id)',
    refs: ['lore_archivist_3', 'lore_map_margin'],
    open: 'Down is the way back to the root. Who read the map upside down?',
  },
  {
    id: 'lore_archivist_5',
    title: 'TRC-5 · Trail 5/5',
    body: '[TRAIL TRC-5] 5/5. cache buried as cache_5. hold_5 sits inside. 5 of 5 found. V.',
    source: '/archivist_5',
    layer: 'layer 05',
    note: '(cache id varies by layer)',
    refs: ['lore_cache', 'lore_hold3'],
    open: 'The count is complete. The archive stays open.',
  },
  {
    id: 'lore_ghost',
    title: 'OPR-09 · Ghost Margin',
    body: '[GHOST OPR-09] margin: password reads /holds/04/README. seen after hold_3 opens. ghost pell-03.',
    source: '/hosts/ghost margin',
    layer: 'layer 01',
    note: '(redacted: checksum, 6 chars)',
    refs: ['lore_hold_seal', 'lore_boot'],
    open: 'Whose margin names your next hold?',
  },
  {
    id: 'lore_hold_seal',
    title: 'VLT-07 · Hold Seal',
    body: '[HOLD VLT-07] Nothing in this node is load-bearing. I checked twice. M.I. layer 04.',
    source: '/holds/README',
    layer: 'layer 01',
    note: '(redacted: author, 6 chars)',
    refs: ['lore_hold_recheck', 'lore_lock'],
    open: 'If nothing here is load-bearing, what did the seal close?',
  },
  {
    id: 'lore_hold_recheck',
    title: 'VLT-12 · Hold Recheck',
    body: '[HOLD VLT-12] nothing load-bearing. checked twice. checked again because I did not believe it.',
    source: '/holds/README',
    layer: 'layer 01',
    note: '(unsigned; same README as VLT-07)',
    refs: ['lore_hold_seal', 'lore_tally'],
    open: 'Two registers, one hand. What failed the first check?',
  },
  {
    id: 'lore_hold3',
    title: 'VLT-05 · hold_3 Seal',
    body: '[HOLD VLT-05] hold_3 sealed 03:10:00 UTC 2038-01-19. checked twice. M.I. layer 03.',
    source: '/holds/03/README',
    layer: 'layer 03',
    note: '(four minutes before the manifest line)',
    refs: ['lore_archivist_2', 'lore_cache'],
    open: 'Sealed 03:10, manifest 03:14. What ran in between?',
  },
  {
    id: 'lore_hold_claim',
    title: 'OPR-03 · Hold Claim',
    body: '[NOTE OPR-03] hold_3 sits on dir_2_3. dated 2038-01-21.',
    source: '/logs/manifest_03',
    layer: 'layer 01',
    note: '(manifest seats hold_3 on the cache_3 host)',
    refs: ['lore_archivist_2', 'lore_manifest'],
    open: 'Lied, misremembered, or overwritten?',
  },
  {
    id: 'lore_cache',
    title: 'LOG-06 · Cache Manifest',
    body: '[CACHE LOG-06] cache_5 capacity 256 MB. seal time matches the hold_5 seal.',
    source: '/cache/cache_manifest',
    layer: 'layer 05',
    note: '(Ibarra claims 512 MB under the same seal time)',
    refs: ['lore_cache_claim', 'lore_hold3'],
    open: 'Same seal time, two capacities. Which manifest closed?',
  },
  {
    id: 'lore_cache_claim',
    title: 'OPR-11 · Capacity Note',
    body: '[SEAL OPR-11] cache_5 capacity 512 MB. checked twice. M.I. layer 05.',
    source: '/logs/capacity_note',
    layer: 'layer 05',
    note: '(manifest lists 256 MB with the same seal timestamp)',
    refs: ['lore_cache', 'lore_lock'],
    open: 'Same hand, same date, different number.',
  },
  {
    id: 'lore_nodes',
    title: 'LOG-05 · Node Listing',
    body: '[NODES LOG-05] three inodes present with no parent since 2038-01-18.',
    source: '/logs/node_list',
    layer: 'layer 04',
    note: '(inodes listed, parents unlisted)',
    refs: ['lore_tally', 'lore_orphan_count'],
    open: 'Present, real, unreachable. Does that count as loss?',
  },
  {
    id: 'lore_tally',
    title: 'OPR-06 · Orphan Tally',
    body: '[TALLY OPR-02] 11 listed, 3 unlisted. count dated 2038-01-18.',
    source: '/logs/tally',
    layer: 'layer 04',
    note: '(Vane count; matches the node listing)',
    refs: ['lore_nodes', 'lore_orphan_count'],
    open: '11 listed. Who lists the 3 unlisted?',
  },
  {
    id: 'lore_orphan_count',
    title: 'OPR-02 · Trail Count',
    body: '[COUNT OPR-02] 11 listed, 3 unlisted. count dated 2038-01-18. V.',
    source: '/archivist_2',
    layer: 'layer 02',
    note: '(travels in the archivist_2 file, beside TRC-2)',
    refs: ['lore_archivist_2', 'lore_tally'],
    open: 'Vane counted on 2038-01-18. What moved since?',
  },
  {
    id: 'lore_hostlog',
    title: 'LOG-07 · Host Log',
    body: '[HOST LOG-07] tictactoe_1 ran on the first host. logged 2038-01-17.',
    source: '/hosts/host_log',
    layer: 'layer 01',
    note: '(Pell margin seats it on the second host)',
    refs: ['lore_second_host', 'lore_archivist_3'],
    open: 'First host or second? Pell never dates margins.',
  },
  {
    id: 'lore_second_host',
    title: 'OPR-13 · Second-Host Claim',
    body: '[MARGIN OPR-13] tictactoe_1 on the second host.',
    source: '/hosts/margin',
    layer: 'layer 01',
    note: '(undated; host log says first)',
    refs: ['lore_hostlog', 'lore_archivist_3'],
    open: 'Which run did Pell watch?',
  },
  {
    id: 'lore_cabinet',
    title: 'OPR-12 · Cabinet Margin',
    body: '[MARGIN OPR-12] cabinet 3 still takes coins, uptime 44d.',
    source: '/hosts/margin',
    layer: 'layer 01',
    note: '(last touched 2038-01-17)',
    refs: ['lore_second_host', 'lore_archivist_4'],
    open: 'Cabinet 3 by number, never by game. Which game pays?',
  },
  {
    id: 'lore_map_margin',
    title: 'OPR-08 · Map Margin',
    body: '[MARGIN OPR-08] down is up because the map is upside down.',
    source: '/hosts/margin',
    layer: 'layer 01',
    note: '(Pell hand, undated)',
    refs: ['lore_archivist_4', 'lore_build'],
    open: 'Lie, prayer, or misread map?',
  },
  {
    id: 'lore_vane_root',
    title: 'OPR-10 · Root Claim',
    body: '[INDEX OPR-10] vane-02 sits on root. 2 of 5 counted. V. 2038-01-14.',
    source: '/logs/index_note',
    layer: 'layer 02',
    note: '(placement log seats vane-02 on an off-path host)',
    refs: ['lore_archivist_1', 'lore_ghost'],
    open: 'Same numbering as the Archivist. Same hand?',
  },
  {
    id: 'lore_lock',
    title: 'OPR-07 · Orphan Lock',
    body: '[LOCK OPR-07] lock held. older than the seal it guards.',
    source: '/logs/carry_lock',
    layer: 'layer 06',
    note: '(held by M.I.; lock older than the seal)',
    refs: ['lore_hold_seal', 'lore_nodes'],
    open: 'Who locked a node before its seal existed?',
  },
  {
    id: 'lore_ascend',
    title: 'LOG-08 · Ascend Tail',
    body: '[ASCEND LOG-08] prior node read-only. tree size plus one.',
    source: '/ascend/tail',
    layer: 'layer 01',
    note: '(tail of every ascend run)',
    refs: ['lore_decay', 'lore_build'],
    open: 'The tree only grows. What does the prior node keep?',
  },
  {
    id: 'lore_offering',
    title: 'OFFER-01 · Offering',
    body: '[OFFER-01] rename a folder archivist, mark it, TRACE inside. the process answers named requests.',
    source: '/archivist (marked folder)',
    layer: 'layer 01',
    note: '(player-made folder; answers once per layer)',
    refs: ['lore_penalty', 'lore_archivist_5'],
    open: 'The process answers named requests. Who else asked?',
  },
  {
    id: 'lore_decay',
    title: 'DECAY-01 · Decay Report',
    body: '[DECAY-01] descent adds a layer. prior node read-only. fuel climbs 25 MB a layer.',
    source: '/boot/manifest',
    layer: 'layer 02',
    note: '(first read on arrival at layer 2)',
    refs: ['lore_ascend', 'lore_end'],
    open: 'Every layer costs more than the last. What is the tree saving?',
  },
  {
    id: 'lore_packages',
    title: 'OPR-04 · Supply Drops',
    body: '[SUPPLY OPR-04] supply_211 from layer 01 unpack. seal torn 2038-01-20. contents listed inside.',
    source: '/supply_211/manifest',
    layer: 'layer 01',
    note: '(redacted: contents line, 1 line)',
    refs: ['lore_modules', 'lore_archivist_1'],
    open: 'Unpacked from an earlier layer. Who packed it?',
  },
  {
    id: 'lore_modules',
    title: 'MOD-01 · Hardware Modules',
    body: '[MOD-01] green modules feed the auto-miner. power per tick, shorter intervals.',
    source: '/mods/hw_mod manifest',
    layer: 'layer 01',
    note: '(redacted: source layer, 2 chars)',
    refs: ['lore_packages', 'lore_cache'],
    open: 'Ibarra never touches modules. Who installed this one?',
  },
  {
    id: 'lore_penalty',
    title: 'PENALTY-01 · Tracer Warning',
    body: '[TRACE PENALTY-01] tracer finds the descend path and nothing else. second scan in one folder burns data.',
    source: '/trace/report',
    layer: 'layer 01',
    note: '(redundant scan penalty, 1-10 MB)',
    refs: ['lore_offering', 'lore_decay'],
    open: 'The second scan costs data and finds nothing. What did the first scan miss?',
  },
  {
    id: 'lore_end',
    title: 'END-01 · What Completion Means',
    body: '[ARCHIVE END-01] every task done, every entry found. the letter waits. the question stays open.',
    source: 'thank-you letter (100%)',
    layer: 'layer 05',
    note: '(100% catalogs; it concludes nothing)',
    refs: ['lore_decay', 'lore_ascend'],
    open: 'Every entry found. Which account do you trust?',
  },
];

export const LORE_TOTAL = LORE_FRAGMENTS.length;

export const loreById = (id: string): LoreFragment | undefined =>
  LORE_FRAGMENTS.find(l => l.id === id);

export const MYSTERY_QUESTIONS: MysteryQuestion[] = [
  {
    id: 'Q1',
    question: 'Did the manifest stop or invert on 2038-01-19?',
    clues: ['lore_boot', 'lore_manifest', 'lore_ghost'],
  },
  {
    id: 'Q2',
    question: 'Is the prior node a record or a remainder?',
    clues: ['lore_archivist_1', 'lore_hold_seal', 'lore_packages'],
  },
  {
    id: 'Q3',
    question: 'Are orphans dead or unreachable?',
    clues: ['lore_tally', 'lore_lock', 'lore_nodes'],
  },
  {
    id: 'Q4',
    question: 'Was the name ascend a lie, a prayer, or a misread map?',
    clues: ['lore_map_margin', 'lore_build', 'lore_archivist_4'],
  },
  {
    id: 'Q5',
    question: 'Who sealed hold_3, and at what capacity?',
    clues: ['lore_hold3', 'lore_hold_claim', 'lore_cache'],
  },
  {
    id: 'Q6',
    question: 'Which terminal host ran cabinet 3?',
    clues: ['lore_second_host', 'lore_hostlog', 'lore_archivist_3'],
  },
  {
    id: 'Q7',
    question: 'Does keeping every layer save the archive or sentence it?',
    clues: ['lore_hold_recheck', 'lore_orphan_count', 'lore_ascend'],
  },
];

export const RESIDUE_THREADS: { label: string; questions: string[] }[] = [
  { label: 'Read-only self as tombstone', questions: ['Q2', 'Q7'] },
  { label: 'Orphan state', questions: ['Q3', 'Q7'] },
  { label: 'Name mismatch', questions: ['Q4', 'Q6'] },
  { label: 'Kill versus refusal', questions: ['Q1', 'Q2'] },
  { label: 'Recovery versus ascension', questions: ['Q1', 'Q2', 'Q4'] },
  { label: 'Memory as mercy or sentence', questions: ['Q3', 'Q5', 'Q7'] },
];
